// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {model} from '../models';

export function CommandExecute(arg1:string,arg2:string,arg3:Array<string>):Promise<types.CommandResult>;

export function CommandGen(arg1:string):Promise<types.CommandResult>;

export function CommandSwagger(arg1:string):Promise<types.CommandResult>;

export function ConfigRead(arg1:string):Promise<model.JZeroConfig>;

export function ConfigValidate(arg1:string):Promise<boolean>;

export function ConfigWrite(arg1:string,arg2:model.JZeroConfig):Promise<void>;

export function FileCreate(arg1:string,arg2:boolean):Promise<void>;

export function FileDelete(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function FileInfo(arg1:string):Promise<types.FileInfo>;

export function FileList(arg1:string,arg2:string):Promise<Array<types.FileInfo>>;

export function FileRead(arg1:string):Promise<string>;

export function FileRename(arg1:string,arg2:string):Promise<void>;

export function FileTree(arg1:string,arg2:string):Promise<Array<types.FileNode>>;

export function FileWrite(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ProjectGen(arg1:string):Promise<string>;

export function ProjectInfo(arg1:string):Promise<types.ProjectInfo>;

export function ProjectList():Promise<Array<types.ProjectInfo>>;

export function ProjectScan(arg1:string):Promise<Array<types.ProjectNode>>;
