// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommandExecute(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommandExecute'](arg1, arg2, arg3);
}

export function CommandGen(arg1) {
  return window['go']['main']['App']['CommandGen'](arg1);
}

export function CommandSwagger(arg1) {
  return window['go']['main']['App']['CommandSwagger'](arg1);
}

export function ConfigRead(arg1) {
  return window['go']['main']['App']['ConfigRead'](arg1);
}

export function ConfigValidate(arg1) {
  return window['go']['main']['App']['ConfigValidate'](arg1);
}

export function ConfigWrite(arg1, arg2) {
  return window['go']['main']['App']['ConfigWrite'](arg1, arg2);
}

export function FileCreate(arg1, arg2) {
  return window['go']['main']['App']['FileCreate'](arg1, arg2);
}

export function FileDelete(arg1) {
  return window['go']['main']['App']['FileDelete'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function FileInfo(arg1) {
  return window['go']['main']['App']['FileInfo'](arg1);
}

export function FileList(arg1, arg2) {
  return window['go']['main']['App']['FileList'](arg1, arg2);
}

export function FileRead(arg1) {
  return window['go']['main']['App']['FileRead'](arg1);
}

export function FileRename(arg1, arg2) {
  return window['go']['main']['App']['FileRename'](arg1, arg2);
}

export function FileTree(arg1, arg2) {
  return window['go']['main']['App']['FileTree'](arg1, arg2);
}

export function FileWrite(arg1, arg2) {
  return window['go']['main']['App']['FileWrite'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProjectGen(arg1) {
  return window['go']['main']['App']['ProjectGen'](arg1);
}

export function ProjectInfo(arg1) {
  return window['go']['main']['App']['ProjectInfo'](arg1);
}

export function ProjectList() {
  return window['go']['main']['App']['ProjectList']();
}

export function ProjectScan(arg1) {
  return window['go']['main']['App']['ProjectScan'](arg1);
}
